const sessionActionTypes = {
  AUTHENTICATION_START: "AUTHENTICATION_START",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAILURE: "AUTHENTICATION_FAILURE",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  GOOGLE_SIGN_IN_SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",
  GOOGLE_SIGN_IN_FAILURE: "GOOGLE_SIGN_IN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  LOGGED_OUT: "LOGGED_OUT",
};

export default sessionActionTypes;
