const chatManagerActionTypes = {
  ADD_CHANNEL_START: "ADD_CHANNEL_START",
  ADD_CHANNEL_SUCCESS: "ADD_CHANNEL_SUCCESS",
  ADD_CHANNEL_FAILURE: "ADD_CHANNEL_FAILURE",
  GET_CHANNELS_COLLECTION_START: "GET_CHANNELS_COLLECTION_START",
  GET_CHANNELS_COLLECTION_SUCCESS: "GET_CHANNELS_COLLECTION_SUCCESS",
  GET_CHANNELS_COLLECTION_FAILURE: "GET_CHANNELS_COLLECTION_FAILURE",
  SET_CHANNEL_ID: "SET_CHANNEL_ID",
  SEND_MESSAGE_START: "SEND_MESSAGE_START",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE",
  GET_CHANNEL_DETAILS_START: "GET_CHANNEL_DETAILS_START",
  GET_CHANNEL_DETAILS_SUCCESS: "GET_CHANNEL_DETAILS_SUCCESS",
  GET_CHANNEL_DETAILS_FAILURE: "GET_CHANNEL_DETAILS_FAILURE",
  GET_MESSAGES_START: "GET_MESSAGES_START",
  GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  GET_MESSAGES_FAILURE: "GET_MESSAGES_FAILURE",
};

export default chatManagerActionTypes;
